"""empty message

Revision ID: 216db9fbf14b
Revises: 9c623532af08
Create Date: 2024-09-30 11:22:37.642729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216db9fbf14b'
down_revision = '9c623532af08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index('ix_skills_name')

    op.drop_table('skills')
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('body_content',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('body_content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               nullable=True)

    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='skills_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='skills_pkey')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index('ix_skills_name', ['name'], unique=True)

    # ### end Alembic commands ###
